services:
  - type: web
    name: splitter-ai-backend
    env: python
    region: oregon # Choose the region closest to your users
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.17 # Version compatible with Spleeter 2.1.0 and TensorFlow 2.8
      - key: SUPABASE_URL
        sync: false # You'll need to set this in Render dashboard
      - key: SUPABASE_KEY
        sync: false # You'll need to set this in Render dashboard
    autoDeploy: true
    healthCheckPath: /health
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    # Use Render's package management
    packages:
      - ffmpeg
      - libsndfile1
