services:
  - type: web
    name: splitter-ai-backend
    env: python
    region: oregon # Choose the region closest to your users
    buildCommand: |
      # Install system dependencies
      apt-get update && apt-get install -y ffmpeg libsndfile1
      # Install Python dependencies
      pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.12
      - key: SUPABASE_URL
        sync: false # You'll need to set this in Render dashboard
      - key: SUPABASE_KEY
        sync: false # You'll need to set this in Render dashboard
    autoDeploy: true
    healthCheckPath: /health
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
