services:
  - type: web
    name: splitter-ai-backend
    env: python
    region: oregon # Choose the region closest to your users
    buildCommand: |
      # Install system dependencies
      apt-get update && apt-get install -y \
        ffmpeg \
        libsndfile1 \
        build-essential \
        python3-dev \
        python3-pip \
        python3-setuptools \
        python3-wheel \
        gfortran \
        libopenblas-dev \
        liblapack-dev \
        pkg-config \
        cmake \
        gcc \
        g++ \
        git
      # Set environment variables for numpy build
      export CFLAGS="-I/usr/include/python3.11 -I/usr/local/include/python3.11"
      export LDFLAGS="-L/usr/lib/python3.11 -L/usr/local/lib/python3.11"
      # Upgrade pip and install build tools
      pip install --upgrade pip setuptools wheel
      # Install numpy with specific build options
      pip install --no-binary :all: numpy==1.24.3 --config-settings="--build-option=-j4"
      # Install PyTorch CPU version (smaller and faster to install)
      pip install torch==2.1.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cpu
      # Install remaining requirements
      pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7 # Latest Python 3.11 version
      - key: SUPABASE_URL
        sync: false # You'll need to set this in Render dashboard
      - key: SUPABASE_KEY
        sync: false # You'll need to set this in Render dashboard
      - key: OPENBLAS_NUM_THREADS
        value: "1"
      - key: MKL_NUM_THREADS
        value: "1"
      - key: PYTHONPATH
        value: "/usr/local/lib/python3.11/site-packages:/usr/lib/python3.11/site-packages"
    autoDeploy: true
    healthCheckPath: /health
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
